NAME             OFFSET KND SCP FLAG TYPE
args                    arr glb r    any (unknown) by ref (size 0)
uregs                   arr glb r    D type (integer) (size 8)
curthread               scl glb r    D type (pointer) (size 8)
timestamp               scl glb r    D type (integer) (size 8)
vtimestamp              scl glb r    D type (integer) (size 8)
ipl                     scl glb r    D type (integer) (size 4)
epid                    scl glb r    D type (integer) (size 4)
id                      scl glb r    D type (integer) (size 4)
arg0                    scl glb r    D type (integer) (size 8)
arg1                    scl glb r    D type (integer) (size 8)
arg2                    scl glb r    D type (integer) (size 8)
arg3                    scl glb r    D type (integer) (size 8)
arg4                    scl glb r    D type (integer) (size 8)
arg5                    scl glb r    D type (integer) (size 8)
arg6                    scl glb r    D type (integer) (size 8)
arg7                    scl glb r    D type (integer) (size 8)
arg8                    scl glb r    D type (integer) (size 8)
arg9                    scl glb r    D type (integer) (size 8)
stackdepth              scl glb r    D type (integer) (size 4)
caller                  scl glb r    D type (integer) (size 8)
probeprov               scl glb r    string (unknown) by ref (size 256)
probemod                scl glb r    string (unknown) by ref (size 256)
probefunc               scl glb r    string (unknown) by ref (size 256)
probename               scl glb r    string (unknown) by ref (size 256)
pid                     scl glb r    D type (integer) (size 4)
tid                     scl glb r    D type (integer) (size 4)
execname                scl glb r    string (unknown) by ref (size 256)
walltimestamp           scl glb r    D type (integer) (size 8)
ustackdepth             scl glb r    D type (integer) (size 4)
ucaller                 scl glb r    D type (integer) (size 8)
ppid                    scl glb r    D type (integer) (size 4)
uid                     scl glb r    D type (integer) (size 4)
gid                     scl glb r    D type (integer) (size 4)
errno                   scl glb r    D type (integer) (size 4)
curcpu                  scl glb r    D type (pointer) (size 8)
