#!/bin/bash
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

if [[ -z $LOOP ]]; then
    export LOOP=0
fi

if [[ $LOOP -eq 10000000 ]]; then
    exit 0
fi

LOOP=$(($LOOP+1))

exec $0
