/*
 * Generated by dtrace(1M).
 */

#ifndef	_USDT_TST_ARGS_PROV_H
#define	_USDT_TST_ARGS_PROV_H

#include <unistd.h>
#include <inttypes.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define _DTRACE_VERSION 1

#if _DTRACE_VERSION

#define	TEST_PROV_PLACE(arg0, arg1) \
	__dtrace_test_prov___place(arg0, arg1)
#ifndef	__sparc
#define	TEST_PROV_PLACE_ENABLED() \
	__dtraceenabled_test_prov___place()
#else
#define	TEST_PROV_PLACE_ENABLED() \
	__dtraceenabled_test_prov___place(0)
#endif


extern void __dtrace_test_prov___place(int, int);
#ifndef	__sparc
extern int __dtraceenabled_test_prov___place(void);
#else
extern int __dtraceenabled_test_prov___place(long);
#endif

#else

#define	TEST_PROV_PLACE(arg0, arg1)
#define	TEST_PROV_PLACE_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _USDT_TST_ARGS_PROV_H */
