/*
 * Generated by dtrace(1M).
 */

#ifndef	_USDT_TST_FORKER_PROV_H
#define	_USDT_TST_FORKER_PROV_H

#include <unistd.h>
#include <inttypes.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define _DTRACE_VERSION 1

#if _DTRACE_VERSION

#define	FORKER_FIRE() \
	__dtrace_forker___fire()
#ifndef	__sparc
#define	FORKER_FIRE_ENABLED() \
	__dtraceenabled_forker___fire()
#else
#define	FORKER_FIRE_ENABLED() \
	__dtraceenabled_forker___fire(0)
#endif


extern void __dtrace_forker___fire(void);
#ifndef	__sparc
extern int __dtraceenabled_forker___fire(void);
#else
extern int __dtraceenabled_forker___fire(long);
#endif

#else

#define	FORKER_FIRE()
#define	FORKER_FIRE_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _USDT_TST_FORKER_PROV_H */
