#!/bin/bash
# Attempt to load the appropriate DTrace module for this kernel.
#

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2013 Oracle, Inc.  All rights reserved.
# Use is subject to license terms.
#

# Suppress all normal output.
exec >/dev/null

# Can't do anything if non-root.
[[ "$(id -u)" != 0 ]] && exit 1

# First, try to simply modprobe it.

modprobe -q dtrace 2>/dev/null && exit 0

# Not installed. Ask yum for it: print a message first, since this may take
# a while to time out if the network is not up.

echo "Downloading DTrace module..." >&2
yum install -q -y dtrace-modules-$(uname -r)

# One last try to modprobe.

modprobe -q dtrace 2>/dev/null
