#!/bin/bash
# Attempt to load the appropriate DTrace module for this kernel.
#
# Also load any modules named in /etc/dtrace-modules.  Failure to
# load these is not fatal (nor even reported).
#

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2013, 2014, 2017 Oracle, Inc.  All rights reserved.
# Use is subject to license terms.
#

load_modules()
{
    if ! modprobe -q dtrace 2>/dev/null; then
        return 1
    fi

    test -f ${DTRACE_MODULES_CONF:-/etc/dtrace-modules} || return 0

    # Failure to load modules from /etc/dtrace-modules is nonfatal.
    cat ${DTRACE_MODULES_CONF:-/etc/dtrace-modules} | sed 's,\(.\)#.*$,\1,' | while read -r MODULE; do
        [[ $MODULE =~ ^# ]] && continue;

        modprobe -q $MODULE >/dev/null 2>&1 || true
    done

    return 0
}

# Suppress all normal output.
exec >/dev/null

# Can't do anything if non-root.
[[ "$(id -u)" != 0 ]] && exit 1

# First, try to simply modprobe it.

load_modules && exit 0

# Not installed. Ask yum for it: print a message first, since this may take
# a while to time out if the network is not up.

echo "Downloading DTrace module..." >&2
yum install -q -y dtrace-modules-$(uname -r)

# One last try to modprobe.

load_modules
